/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LovableClientDotjsonRouteImport } from './routes/lovable-client[.]json'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedScoreboardRouteImport } from './routes/_authenticated/scoreboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedVersionsRouteImport } from './routes/_authenticated/versions'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as ApiPublicHarnessCorrectionsRouteImport } from './routes/api/public/harness/corrections'
import { Route as ApiPublicHarnessImprovementsRouteImport } from './routes/api/public/harness/improvements'
import { Route as ApiPublicHarnessRulesRouteImport } from './routes/api/public/harness/rules'
import { Route as ApiPublicHarnessRuntimeRouteImport } from './routes/api/public/harness/runtime'
import { Route as ApiPublicHooksQueueWorkerRouteImport } from './routes/api/public/hooks/queue-worker'
import { Route as ApiPublicLovableConnectionRouteImport } from './routes/api/public/lovable/connection'
import { Route as ApiPublicLovableOauthCallbackRouteImport } from './routes/api/public/lovable/oauth-callback'
import { Route as ApiPublicLovableOauthRefreshRouteImport } from './routes/api/public/lovable/oauth-refresh'
import { Route as ApiPublicLovableOauthStartRouteImport } from './routes/api/public/lovable/oauth-start'
import { Route as ApiPublicLovableSyncProjectsRouteImport } from './routes/api/public/lovable/sync-projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableClientDotjsonRoute = LovableClientDotjsonRouteImport.update({
  id: '/lovable-client.json',
  path: '/lovable-client.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScoreboardRoute = AuthenticatedScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVersionsRoute = AuthenticatedVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHarnessCorrectionsRoute =
  ApiPublicHarnessCorrectionsRouteImport.update({
    id: '/api/public/harness/corrections',
    path: '/api/public/harness/corrections',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHarnessImprovementsRoute =
  ApiPublicHarnessImprovementsRouteImport.update({
    id: '/api/public/harness/improvements',
    path: '/api/public/harness/improvements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHarnessRulesRoute = ApiPublicHarnessRulesRouteImport.update({
  id: '/api/public/harness/rules',
  path: '/api/public/harness/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHarnessRuntimeRoute = ApiPublicHarnessRuntimeRouteImport.update({
  id: '/api/public/harness/runtime',
  path: '/api/public/harness/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksQueueWorkerRoute =
  ApiPublicHooksQueueWorkerRouteImport.update({
    id: '/api/public/hooks/queue-worker',
    path: '/api/public/hooks/queue-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLovableConnectionRoute =
  ApiPublicLovableConnectionRouteImport.update({
    id: '/api/public/lovable/connection',
    path: '/api/public/lovable/connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLovableOauthCallbackRoute =
  ApiPublicLovableOauthCallbackRouteImport.update({
    id: '/api/public/lovable/oauth-callback',
    path: '/api/public/lovable/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLovableOauthRefreshRoute =
  ApiPublicLovableOauthRefreshRouteImport.update({
    id: '/api/public/lovable/oauth-refresh',
    path: '/api/public/lovable/oauth-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLovableOauthStartRoute =
  ApiPublicLovableOauthStartRouteImport.update({
    id: '/api/public/lovable/oauth-start',
    path: '/api/public/lovable/oauth-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLovableSyncProjectsRoute =
  ApiPublicLovableSyncProjectsRouteImport.update({
    id: '/api/public/lovable/sync-projects',
    path: '/api/public/lovable/sync-projects',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lovable-client.json': typeof LovableClientDotjsonRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/scoreboard': typeof AuthenticatedScoreboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/api/public/harness/corrections': typeof ApiPublicHarnessCorrectionsRoute
  '/api/public/harness/improvements': typeof ApiPublicHarnessImprovementsRoute
  '/api/public/harness/rules': typeof ApiPublicHarnessRulesRoute
  '/api/public/harness/runtime': typeof ApiPublicHarnessRuntimeRoute
  '/api/public/hooks/queue-worker': typeof ApiPublicHooksQueueWorkerRoute
  '/api/public/lovable/connection': typeof ApiPublicLovableConnectionRoute
  '/api/public/lovable/oauth-callback': typeof ApiPublicLovableOauthCallbackRoute
  '/api/public/lovable/oauth-refresh': typeof ApiPublicLovableOauthRefreshRoute
  '/api/public/lovable/oauth-start': typeof ApiPublicLovableOauthStartRoute
  '/api/public/lovable/sync-projects': typeof ApiPublicLovableSyncProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/lovable-client.json': typeof LovableClientDotjsonRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/scoreboard': typeof AuthenticatedScoreboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/api/public/harness/corrections': typeof ApiPublicHarnessCorrectionsRoute
  '/api/public/harness/improvements': typeof ApiPublicHarnessImprovementsRoute
  '/api/public/harness/rules': typeof ApiPublicHarnessRulesRoute
  '/api/public/harness/runtime': typeof ApiPublicHarnessRuntimeRoute
  '/api/public/hooks/queue-worker': typeof ApiPublicHooksQueueWorkerRoute
  '/api/public/lovable/connection': typeof ApiPublicLovableConnectionRoute
  '/api/public/lovable/oauth-callback': typeof ApiPublicLovableOauthCallbackRoute
  '/api/public/lovable/oauth-refresh': typeof ApiPublicLovableOauthRefreshRoute
  '/api/public/lovable/oauth-start': typeof ApiPublicLovableOauthStartRoute
  '/api/public/lovable/sync-projects': typeof ApiPublicLovableSyncProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/lovable-client.json': typeof LovableClientDotjsonRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/scoreboard': typeof AuthenticatedScoreboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/versions': typeof AuthenticatedVersionsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/api/public/harness/corrections': typeof ApiPublicHarnessCorrectionsRoute
  '/api/public/harness/improvements': typeof ApiPublicHarnessImprovementsRoute
  '/api/public/harness/rules': typeof ApiPublicHarnessRulesRoute
  '/api/public/harness/runtime': typeof ApiPublicHarnessRuntimeRoute
  '/api/public/hooks/queue-worker': typeof ApiPublicHooksQueueWorkerRoute
  '/api/public/lovable/connection': typeof ApiPublicLovableConnectionRoute
  '/api/public/lovable/oauth-callback': typeof ApiPublicLovableOauthCallbackRoute
  '/api/public/lovable/oauth-refresh': typeof ApiPublicLovableOauthRefreshRoute
  '/api/public/lovable/oauth-start': typeof ApiPublicLovableOauthStartRoute
  '/api/public/lovable/sync-projects': typeof ApiPublicLovableSyncProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/lovable-client.json'
    | '/demo'
    | '/inbox'
    | '/jobs'
    | '/ledger'
    | '/overview'
    | '/projects'
    | '/scoreboard'
    | '/settings'
    | '/versions'
    | '/oauth/callback'
    | '/api/public/harness/corrections'
    | '/api/public/harness/improvements'
    | '/api/public/harness/rules'
    | '/api/public/harness/runtime'
    | '/api/public/hooks/queue-worker'
    | '/api/public/lovable/connection'
    | '/api/public/lovable/oauth-callback'
    | '/api/public/lovable/oauth-refresh'
    | '/api/public/lovable/oauth-start'
    | '/api/public/lovable/sync-projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/lovable-client.json'
    | '/demo'
    | '/inbox'
    | '/jobs'
    | '/ledger'
    | '/overview'
    | '/projects'
    | '/scoreboard'
    | '/settings'
    | '/versions'
    | '/oauth/callback'
    | '/api/public/harness/corrections'
    | '/api/public/harness/improvements'
    | '/api/public/harness/rules'
    | '/api/public/harness/runtime'
    | '/api/public/hooks/queue-worker'
    | '/api/public/lovable/connection'
    | '/api/public/lovable/oauth-callback'
    | '/api/public/lovable/oauth-refresh'
    | '/api/public/lovable/oauth-start'
    | '/api/public/lovable/sync-projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/lovable-client.json'
    | '/_authenticated/demo'
    | '/_authenticated/inbox'
    | '/_authenticated/jobs'
    | '/_authenticated/ledger'
    | '/_authenticated/overview'
    | '/_authenticated/projects'
    | '/_authenticated/scoreboard'
    | '/_authenticated/settings'
    | '/_authenticated/versions'
    | '/oauth/callback'
    | '/api/public/harness/corrections'
    | '/api/public/harness/improvements'
    | '/api/public/harness/rules'
    | '/api/public/harness/runtime'
    | '/api/public/hooks/queue-worker'
    | '/api/public/lovable/connection'
    | '/api/public/lovable/oauth-callback'
    | '/api/public/lovable/oauth-refresh'
    | '/api/public/lovable/oauth-start'
    | '/api/public/lovable/sync-projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LovableClientDotjsonRoute: typeof LovableClientDotjsonRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ApiPublicHarnessCorrectionsRoute: typeof ApiPublicHarnessCorrectionsRoute
  ApiPublicHarnessImprovementsRoute: typeof ApiPublicHarnessImprovementsRoute
  ApiPublicHarnessRulesRoute: typeof ApiPublicHarnessRulesRoute
  ApiPublicHarnessRuntimeRoute: typeof ApiPublicHarnessRuntimeRoute
  ApiPublicHooksQueueWorkerRoute: typeof ApiPublicHooksQueueWorkerRoute
  ApiPublicLovableConnectionRoute: typeof ApiPublicLovableConnectionRoute
  ApiPublicLovableOauthCallbackRoute: typeof ApiPublicLovableOauthCallbackRoute
  ApiPublicLovableOauthRefreshRoute: typeof ApiPublicLovableOauthRefreshRoute
  ApiPublicLovableOauthStartRoute: typeof ApiPublicLovableOauthStartRoute
  ApiPublicLovableSyncProjectsRoute: typeof ApiPublicLovableSyncProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable-client.json': {
      id: '/lovable-client.json'
      path: '/lovable-client.json'
      fullPath: '/lovable-client.json'
      preLoaderRoute: typeof LovableClientDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scoreboard': {
      id: '/_authenticated/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof AuthenticatedScoreboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versions': {
      id: '/_authenticated/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof AuthenticatedVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/harness/corrections': {
      id: '/api/public/harness/corrections'
      path: '/api/public/harness/corrections'
      fullPath: '/api/public/harness/corrections'
      preLoaderRoute: typeof ApiPublicHarnessCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/harness/improvements': {
      id: '/api/public/harness/improvements'
      path: '/api/public/harness/improvements'
      fullPath: '/api/public/harness/improvements'
      preLoaderRoute: typeof ApiPublicHarnessImprovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/harness/rules': {
      id: '/api/public/harness/rules'
      path: '/api/public/harness/rules'
      fullPath: '/api/public/harness/rules'
      preLoaderRoute: typeof ApiPublicHarnessRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/harness/runtime': {
      id: '/api/public/harness/runtime'
      path: '/api/public/harness/runtime'
      fullPath: '/api/public/harness/runtime'
      preLoaderRoute: typeof ApiPublicHarnessRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/queue-worker': {
      id: '/api/public/hooks/queue-worker'
      path: '/api/public/hooks/queue-worker'
      fullPath: '/api/public/hooks/queue-worker'
      preLoaderRoute: typeof ApiPublicHooksQueueWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lovable/connection': {
      id: '/api/public/lovable/connection'
      path: '/api/public/lovable/connection'
      fullPath: '/api/public/lovable/connection'
      preLoaderRoute: typeof ApiPublicLovableConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lovable/oauth-callback': {
      id: '/api/public/lovable/oauth-callback'
      path: '/api/public/lovable/oauth-callback'
      fullPath: '/api/public/lovable/oauth-callback'
      preLoaderRoute: typeof ApiPublicLovableOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lovable/oauth-refresh': {
      id: '/api/public/lovable/oauth-refresh'
      path: '/api/public/lovable/oauth-refresh'
      fullPath: '/api/public/lovable/oauth-refresh'
      preLoaderRoute: typeof ApiPublicLovableOauthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lovable/oauth-start': {
      id: '/api/public/lovable/oauth-start'
      path: '/api/public/lovable/oauth-start'
      fullPath: '/api/public/lovable/oauth-start'
      preLoaderRoute: typeof ApiPublicLovableOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lovable/sync-projects': {
      id: '/api/public/lovable/sync-projects'
      path: '/api/public/lovable/sync-projects'
      fullPath: '/api/public/lovable/sync-projects'
      preLoaderRoute: typeof ApiPublicLovableSyncProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedScoreboardRoute: typeof AuthenticatedScoreboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVersionsRoute: typeof AuthenticatedVersionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedScoreboardRoute: AuthenticatedScoreboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVersionsRoute: AuthenticatedVersionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LovableClientDotjsonRoute: LovableClientDotjsonRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ApiPublicHarnessCorrectionsRoute: ApiPublicHarnessCorrectionsRoute,
  ApiPublicHarnessImprovementsRoute: ApiPublicHarnessImprovementsRoute,
  ApiPublicHarnessRulesRoute: ApiPublicHarnessRulesRoute,
  ApiPublicHarnessRuntimeRoute: ApiPublicHarnessRuntimeRoute,
  ApiPublicHooksQueueWorkerRoute: ApiPublicHooksQueueWorkerRoute,
  ApiPublicLovableConnectionRoute: ApiPublicLovableConnectionRoute,
  ApiPublicLovableOauthCallbackRoute: ApiPublicLovableOauthCallbackRoute,
  ApiPublicLovableOauthRefreshRoute: ApiPublicLovableOauthRefreshRoute,
  ApiPublicLovableOauthStartRoute: ApiPublicLovableOauthStartRoute,
  ApiPublicLovableSyncProjectsRoute: ApiPublicLovableSyncProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
